# Assumes working directory is the directory of this script
source('cachematrix.R')

input.matrix <- matrix(sample(0:9, 9, replace = TRUE), 3, 3)
cm <- makeCacheMatrix(input.matrix)
print("Input matrix:")
cm$get()
print("Determinant:")
det(input.matrix)
print("Inverse initially:")
cm$getinverse()
print("Inverse after calc:")
cacheSolve(cm)
print("Try inverting the index again:")
cacheSolve(cm)
print("Cached inverse:")
cm$getinverse()